version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Spandan_db
    ports:
      - "4000:3306"
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "4001:80"
    depends_on:
      - mysql
    stdin_open: true
    tty: true